# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Transforming_Observable_Sequences' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Transforming_Observable_Sequences
  pod 'RxSwift', '~> 4.2'

end
