# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BindDataToUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BindDataToUI
  pod 'RxCocoa', '~> 4.3'
  pod 'RxSwift', '~> 4.3'

  target 'BindDataToUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
