# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'FilteringObservableSequences' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FilteringObservableSequences

pod 'RxSwift', '~> 4.2'
end
